dist: trusty

language: bash

addons:
    apt_packages:
        - build-essential
        - git
        - curl

cache:
    directories:
        - $HOME/download/
        - $HOME/miniconda3/

before_install:
  - bash .travis/travis_before_install.sh


install:

script:
  - export PATH="$HOME/miniconda/bin:$PATH"
  - echo $PATH
  - source activate smsk
  - snakemake --use-conda -j
